import gzip
import xml.etree.ElementTree as ET
from datetime import datetime
import sys

SOURCE_GZ = "epg_ripper_ALL_SOURCES1.gz"
OUTPUT_XML = "filtered_epg.xml"
OUTPUT_GZ  = "filtered_epg.xml.gz"


# ✅ Your exact channel list
CHANNELS = {
"24.GHANTA.in",
"7S.MUSIC.in",
"9X.Jalwa.in",
"9X.JHAKAAS.in",
"9XM.in",
"9X.TASHAN.in",
"AADINATH.in",
"AAJ.TAK.in",
"AAKASH.AATH.in",
"Aastha.bhajan.in",
"Aastha.Gujarati.in",
"AASTHA.in",
"Aastha.Kannada.in",
"Aastha.Tamil.in",
"Aastha.Telugu.in",
"ABN.ANDHRA.JYOTHI.in",
"ABP.ANANDA.in",
"ABP.ASMITA.in",
"ABP.MAJHA.in",
"ABP.NEWS.in",
"ADITHYA.TV.in",
"ALANKAR.in",
"ALJAZEERA.in",
"AMRITA.in",
"and.Flix.HD.in",
"and.flix.in",
"and.PICTURES.HD.in",
"and.PICTURES.in",
"and.PRIVE.HD.in",
"and.TV.HD.in",
"and.TV.in",
"and.xplorHD.in",
"ANIMAL.PLANET.HD.WORLD.in",
"ANIMAL.PLANET.in",
"ARADANA.in",
"ARGUS.in",
"ASIANET.HD.in",
"ASIANET.in",
"ASIANET.MOVIES.HD.in",
"ASIANET.MOVIES.in",
"ASIANET.NEWS.in",
"ASIANET.PLUS.in",
"ASIANET.SUVARNA.NEWS.in",
"Ayushmaan.Active.in",
"AYUSH.TV.in",
"B4U.KADAK.in",
"B4U.Movies.in",
"B4U.MUSIC.in",
"BALLE.BALLE.in",
"BBC.World.News.in",
"BEST.RECHARGE.OFFER.in",
"BHAKTI.ACTIVE.in",
"BHAKTI.TV.in",
"BHARAT.EXPRESS.in",
"BHOJPURI.CINEMA.in",
"BIG.MAGIC.in",
"Calcutta.News.in",
"CARTOON.NETWORK.in",
"Chardikala.Time.TV.in",
"CHINTU.TV.in",
"CHUMBAK.TV.in",
"CHUTTI.TV.in",
"CINE.ACTIVE.in",
"CNBC.AWAAZ.in",
"CNBC.BAJAR.in",
"CNBC.TV18.in",
"CNBC.TV18.Prime.in",
"CNN.INTERNATIONAL.in",
"CNN.NEWS.18.in",
"COLORS.BANGLA.CINEMA.in",
"COLORS.BANGLA.HD.in",
"COLORS.BANGLA.in",
"COLORS.CINEPLEX.in",
"COLORS.CINEPLEX.SUPERHITS.in",
"COLORS.GUJARATI.CINEMA.in",
"COLORS.GUJARATI.in",
"COLORS.HD.in",
"COLORS.in",
"COLORS.INFINITY.HD.in",
"COLORS.INFINITY..in",
"COLORS.KANNADA.HD.in",
"COLORS.KANNADA.in",
"COLORS.KANNADA.MOVIES.in",
"COLORS.MARATHI.HD.in",
"COLORS.MARATHI.in",
"COLORS.RISHTEY.in",
"COLORS.SUPER.in",
"COLORS.TAMIL.HD.in",
"Colors.Tamil.in",
"COMEDY.ACTIVE.in",
"COOKING.ACTIVE.in",
"CTVN-AKD-Plus.in",
"CUSTOMER.CARE.in",
"D2H.Update.in",
"Dangal.2.in",
"DANGAL.in",
"DARSHANA.in",
"DD.ARUN.PRABHA.in",
"DD.Bangla.in",
"DD.BHARTI.in",
"DD.BIHAR.in",
"DD.Chandana.in",
"DD.GIRNAR.in",
"DD.INDIA.in",
"DD.Kashir.in",
"DD.Kisan.in",
"DD.MALAYALAM.in",
"DD.MP.in",
"DD.National.in",
"DD.NEWS.in",
"DD.North.east.in",
"DD.ODIA.in",
"DD.PUNJABI.in",
"DD.RAJASTHAN.in",
"DD.SAHYADRI.in",
"DD.Saptagiri.in",
"DD.Sports.in",
"DD.TAMIL.in",
"DD.UP.in",
"DD.URDU.in",
"DD.YADAGIRI.in",
"DHOOM.MUSIC.in",
"DISCOVERY.CHANNEL.in",
"DISCOVERY.HD.WORLD.in",
"DISCOVERY.KIDS.in",
"Discovery.Science.in",
"Discovery.Turbo.in",
"DISNEY.CHANNEL.in",
"DISNEY.JUNIOR.in",
"DTAMIL.in",
"DY365.in",
"ENTER10.BANGLA.in",
"EPIC.TV.in",
"ET.NOW.in",
"ET.NOW.SWADESH.in",
"ETV.ABHIRUCHI.in",
"ETV.ANDHRA.PRADESH.in",
"ETV.BAL.BHARAT.in",
"ETV.CINEMA.in",
"ETV.HD.in",
"ETV.LIFE.in",
"ETV.PLUS.in",
"ETV.TELANGANA.in",
"ETV.TELUGU.in",
"Eurosport.in",
"EUROSPORTS.HD.in",
"EVERGREEN.CLASSICS.ACTIVE.in",
"FAKT.MARATHI.in",
"Filamchi.in",
"Fitness.Active.in",
"FLOWERS.in",
"GEMINI.COMEDY.in",
"GEMINI.LIFE.in",
"GEMINI.MOVIES.in",
"GEMINI.MUSIC.in",
"GEMINI.TV.HD.in",
"GEMINI.TV.in",
"GOODNESS.TV.in",
"Gubbare.in",
"GULISTAN.NEWS.in",
"HINDU.DHARMAM.in",
"HISTORY.CHANNEL.in",
"HISTORY.TV18.HD.in",
"Hits.Active.in",
"HM.TV.in",
"HOLLYWOOD.INDIE.ACTIVE.in",
"HOME.CHANNEL.1.1ST.LCN.in",
"HOME.CHANNEL.1.2ND.LCN.in",
"HOME.CHANNEL.1.3RD.LCN.in",
"HOME.CHANNEL.2.in",
"HOME.CHANNEL.HD.Duplicate1.in",
"HOME.CHANNEL.HD.Duplicate.in",
"HOME.CHANNEL.HD.in",
"HUNGAMA.in",
"India.News.Haryana.in",
"India.News.in",
"INDIA.TODAY.in",
"INDIA.TV.in",
"Investigation.Discovery.in",
"ISAI.ARUVI.in",
"Ishara.TV.in",
"ISHWAR.BHAKTI.in",
"JAI.HIND.in",
"JALSHA.MOVIES.HD.in",
"JALSHA.MOVIES.in",
"JANAM.TV.in",
"JAYA.MAX.in",
"JAYA.PLUS.in",
"JAYA.TV.in",
"JINVANI.TV.in",
"JK.24X7.NEWS.in",
"J.MOVIE.in",
"KAIRALI.in",
"KAIRALI.NEWS.in",
"KALAIGNAR.CHITHIRAM.in",
"KALAIGNAR.in",
"KALINGA.TV.in",
"KANAK.NEWS.in",
"KANNADA.NAAPTOL.in",
"KAUMUDY.in",
"KHUSHI.TV.in",
"Kids.Active.Rhymes.in",
"KIDS.ACTIVE.TOONS.in",
"KOCHU.TV.in",
"KOLKATA.TV.in",
"KOREAN.DRAMA.ACTIVE.in",
"K.TV.HD.in",
"KTV.in",
"LOKSHAHI.in",
"MADHA.TV.in",
"MALAI.MURASU.SEITHIKAL.in",
"MALAMAAL.REWARD.in",
"MANORAMA.NEWS.in",
"MATHRUBHUMI.NEWS.in",
"MAX.HD.in",
"MAZHAVIL.MANORAMA.HD.in",
"MAZHAVIL.MANORAMA.in",
"MBC.TV.in",
"MEDIA.ONE.in",
"MEGA.24.in",
"MEGA.MUSIQ.in",
"MEGA.TV.in",
"MH.ONE.in",
"MIRROR.NOW.in",
"MN+.HD.in",
"MNX.in",
"MOVIES.ACTIVE.SD.in",
"MOVIES.NOW.in",
"MTV.in",
"MURASU.in",
"NAMBIKKKAI.in",
"NAT.GEO.WILD.HD.in",
"NAT.GEO.WILD.in",
"NATIONAL.GEOGRAPHIC.HD.in",
"NATIONAL.GEOGRAPHIC.in",
"NDTV.24x7.in",
"NDTV.INDIA.in",
"NDTV.MARATHI.in",
"NEPAL.1.in",
"NEWS18.BANGLA.in",
"NEWS18.BIHAR.JHARKHAND.in",
"NEWS18.GUJARATI.in",
"NEWS18.INDIA.in",
"NEWS18.JAMMU.KASHMIR.LADAKH.HIMACHAL.HARYANA.in",
"NEWS18.KANNADA.in",
"NEWS18.KERALA.in",
"NEWS18.LOKMAT.in",
"NEWS18.MP.CHHATTISGARH.in",
"NEWS18.NORTH.EAST.in",
"NEWS18.ORIYA.in",
"NEWS18.PUNJAB.in",
"NEWS18.RAJASTHAN.in",
"NEWS.18.TAMILNADU.in",
"NEWS18.UTTAR_PRADESH.UTTRANCHAL.in".replace("_","."),
"NEWS.24.in",
"NEWS.FIRST.in",
"NEWS.LIVE.in",
"NEWS.MALAYALAM.24X7.in",
"NEWS.NATION.in",
"News.Tamil.24x7.in",
"NEWS.TIME.BANGLA.in",
"NFDC.-.CINEMAS.OF.INDIA.in",
"NICK.HD+.in",
"NICK.in",
"NICK.JR.in",
"NTV.in",
"OFFER.FOR.YOU.in",
"OTV.in",
"PARAS.GOLD.ONE.in",
"Peace.of.Mind.in",
"Pitaara.in",
"POGO.in",
"POLIMER.in",
"POLIMER.NEWS.in",
"POWER.TV.in",
"POWER.VISION.TV.in",
"PRAMEYA.NEWS7.in",
"PRARTHANA.LIFE.in",
"PRATIDIN.TIME.in",
"PRAVAH.PICTURE.in",
"PTC.CHAK.DE.in",
"PTC.Music.in",
"PTC.NEWS.in",
"PTC.PUNJABI.GOLD.in",
"PTC.PUNJABI.in",
"PTC.Simran.in",
"PUBLIC.MOVIES.in",
"PUBLIC.MUSIC.in",
"PUBLIC.TV.in",
"PUTHIYA.THALAIMURAI.in",
"PUTHU.YUGAM.in",
"RAJ.DIGITAL.PLUS.in",
"RAJ.MUSIX.KANNADA.in",
"RAJ.MUSIX.MALAYALAM.in",
"RAJ.MUSIX.TAMIL.in",
"RAJ.MUSIX.TELUGU.in",
"RAJ.NEWS.KANNADA.in",
"RAJ.NEWS.MALAYALAM.in",
"RAJ.NEWS.TAMIL.in",
"RAJ.NEWS.TELUGU.in",
"RAJ.TV.in",
"RAMDHENU.in",
"RANG.in",
"Rangmanch.Active.in",
"R..Bangla.in",
"RECHARGE.REMINDER.in",
"RENGONI.in",
"REPORTER.in",
"REPUBLIC.BHARAT.in",
"REPUBLIC.TV.in",
"R.KANNADA.in",
"ROMEDY.NOW.in",
"RUPASI.BANGLA.in",
"Russia.Today.in",
"SAAM.in",
"SAB.HD.in",
"Sadhna.in",
"SAFARI.TV.in",
"SAI.LEELA.TV.in",
"SAI.TV.in",
"SAKSHI.TV.in",
"SALAAM.TV.in",
"Sandesh.News.in",
"SANGEET.BANGLA.in",
"SANSAD.TV.1.HD.in",
"SANSAD.TV.1.in",
"SANSAD.TV.2.HD.in",
"SANSAD.TV.2.in",
"SANSKAR.in",
"SATHIYAM.TV.in",
"Satsang.in",
"SEITHIGAL.in",
"SET.HD.in",
"SET.in",
"SHALOM.TV.in",
"Shemaroo.Marathibana.in",
"Shemaroo.TV.in",
"SHEMAROO.UMANG.in",
"SHORTS.TV.ACTIVE.in",
"Showbox.in",
"SHRADDHA.MH1.in",
"SHUBHAVAARTHA.in",
"SIDHARTH.TV.in",
"SIRI.KANNADA-ALL.TIME.in",
"SIRIPOLI.in",
"SMART.BOX.OFFER.DUPLICATE1.in",
"SMART.BOX.OFFER.DUPLICATE.in",
"SMART.BOX.OFFER.in",
"SONGDEW.in",
"SONIC.NICKELODEON.in",
"SONY.AATH.in",
"SONY.BBC.EARTH.HD.in",
"SONY.BBC.EARTH.in",
"Sony.Marathi.in",
"SONY.MAX.1.in",
"SONY.MAX.2.in",
"SONY.MAX.in",
"SONY.PAL.in",
"SONY.PIX.HD.in",
"SONY.PIX.in",
"SONY.SAB.in",
"SONY.SPORTS.TEN.1.HD.in",
"SONY.SPORTS.TEN.1.in",
"SONY.SPORTS.TEN.2.HD.in",
"SONY.SPORTS.TEN.2.in",
"SONY.SPORTS.TEN.3.HD.in",
"SONY.SPORTS.TEN.3.in",
"SONY.SPORTS.TEN.4.TAMIL.in",
"SONY.SPORTS.TEN.5.HD.in",
"SONY.SPORTS.TEN.5.in",
"SONY.WAH.in",
"Sony.yay.in",
"STAR.BHARAT.HD.in",
"STAR.BHARAT.in",
"Star.Gold.2.in",
"STAR.GOLD.HD.in",
"STAR.GOLD.in",
"STAR.GOLD.ROMANCE.in",
"Star.Gold.Select.HD.in",
"STAR.GOLD.SELECT.in",
"STAR.GOLD.THRILLS.in",
"STAR.JALSHA.HD.in",
"STAR.JALSHA.in",
"STAR.KIRAN.in",
"STAR.MAA.GOLD.in",
"STAR.MAA.HD.in",
"STAR.MAA.in",
"STAR.MAA.MOVIES.HD.in",
"STAR.MAA.MOVIES.in",
"STAR.MAA.MUSIC.in",
"STAR.MOVIES.HD.in",
"STAR.MOVIES.in",
"STAR.MOVIES.SELECT.HD.in",
"STAR.MOVIES.SELECT.in",
"STAR.PLUS.HD.in",
"STAR.PLUS.in",
"STAR.PRAVAAH.HD.in",
"STAR.PRAVAH.in",
"STAR.SPORTS.1.HD.HINDI.in",
"STAR.SPORTS.1.HD.in",
"STAR.SPORTS.1.HINDI.in",
"STAR.SPORTS.1.in",
"STAR.SPORTS.1.KANNADA.in",
"STAR.SPORTS.1.TAMIL.HD.in",
"STAR.SPORTS.1.TAMIL.in",
"STAR.SPORTS.1.TELUGU.HD.in",
"STAR.SPORTS.1.TELUGU.in",
"STAR.SPORTS.2.HD.in",
"STAR.SPORTS.2.HINDI.HD.in",
"STAR.SPORTS.2.HINDI.in",
"STAR.SPORTS.2.in",
"STAR.SPORTS.2.KANNADA.in",
"STAR.SPORTS.2.TAMIL.HD.in",
"STAR.SPORTS.2.TAMIL.in",
"STAR.SPORTS.2.TELUGU.HD.in",
"STAR.SPORTS.2.TELUGU.in",
"STAR.SPORTS.3.in",
"Star.Sports.Khel.in",
"STAR.SPORTS.SELECT.1.HD.in",
"Star.Sports.Select.1.in",
"STAR.SPORTS.SELECT.2.HD.in",
"STAR.SPORTS.SELECT.2.in",
"STAR.SUVARNA.HD.in",
"STAR.SUVARNA.in",
"STAR.SUVARNA.PLUS.in",
"STAR.UTSAV.in",
"STAR.UTSAV.MOVIES.in",
"SUDARSHAN.NEWS.in",
"SUN.BANGLA.in",
"SUN.LIFE.in",
"Sun.Marathi.in",
"SUN.MUSIC.HD.in",
"SUN.MUSIC.in",
"Sun.Neo.in",
"SUN.NEWS.in",
"SUN.TV.HD.in",
"SUN.TV.in",
"SUPER.HUNGAMA.in",
"SURYA.COMEDY.in",
"SURYA.HD.in",
"SURYA.MOVIES.in",
"SURYA.MUSIC.in",
"SURYA.TV.in",
"SVBC.2.in",
"SVBC.in",
"TARANG.in",
"TARANG.MUSIC.in",
"TELUGU.ACTIVE.in",
"THANTHI.ONE.in",
"THANTHI.TV.in",
"TIMES.NOW.in",
"TIMES.NOW.NAVBHARAT.in",
"TLC.HD.in",
"TLC.in",
"T.NEWS.in",
"TRAVEL.XP.(SD).in",
"TV5.KANNADA.in",
"TV.5.News.in",
"TV9.Bharatvarsh.in",
"TV9.GUJARATI.in",
"TV9.KANNADA.in",
"TV9.MARATHI.in",
"TV9.TELUGU.in",
"Twenty-Four.in",
"UDAYA.COMEDY.in",
"UDAYA.HD.in",
"UDAYA.MOVIES.in",
"UDAYA.MUSIC.in",
"UDAYA.TV.in",
"V6.NEWS.in",
"VASANTH.TV.in",
"VAS.Promo.Duplicate.in",
"VAS.PROMOS.in",
"VELICHAM.TV.in",
"VIJAY.HD.in",
"VIJAY.SUPER.HD.in",
"VIJAY.SUPER.in",
"VIJAY.TAKKAR.in",
"VIJAY.TV.in",
"VISSA.TV.in",
"VTV.NEWS.in",
"WE.TV.in",
"WION.in",
"Zee.24.Ghanta.in",
"ZEE.24.KALAK.in",
"ZEE.24.TAAS.in",
"ZEE.ACTION.in",
"ZEE.ANMOL.CINEMA.2.in",
"ZEE.ANMOL.CINEMA.in",
"ZEE.ANMOL.in",
"ZEE.BANGLA.CINEMA.in",
"Zee.Bangla.HD.in",
"ZEE.BANGLA.HD.in",
"ZEE.BANGLA.in",
"Zee.Bangla.International.in",
"ZEE.BHARAT.in",
"ZEE.BIHAR.JHARKHAND.in",
"Zee.Bioskop.in",
"Zee.Biskope.in",
"ZEE.Bollywood.in",
"ZEE.BUSINESS.in",
"ZEE.CAFE.HD.in",
"ZEE.CAFE.in",
"ZEE.CINEMA.HD.in",
"ZEE.CINEMA.in",
"ZEE.CINEMALU.HD.in",
"ZEE.CINEMALU.in",
"Zee.Cinema.ME.in",
"Zee.Cinema.UK.in",
"Zee.Cinema.USA.in",
"ZEE.CLASSIC.in",
"ZEE.DELHI.NCR.HARYANA.in",
"ZEE.KANNADA.HD.in",
"ZEE.KANNADA.in",
"ZEE.KERALAM.HD.in",
"ZEE.KERALAM.in",
"Zee.Keralam.ME.in",
"Zee.Madhya.Pradesh.Chhattisgarh.in",
"ZEE.MARATHI.HD.in",
"ZEE.MARATHI.in",
"Zee.Marathi.USA.in",
"ZEE.MP.CHATTISGARH.in",
"Zee.News.in",
"ZEE.NEWS.in",
"Zee.News.Uttar.Pradesh.Uttrakhand.in",
"Zee.Picchar.in",
"ZEE.PUNJAB.HARYANA.HIMACHAL.in",
"Zee.Punjabi.in",
"ZEE.RAJASTHAN.NEWS.in",
"Zee.Salaam.in",
"ZEE.SARTHAK.in",
"ZEE.TALKIES.HD.in",
"ZEE.TALKIES.in",
"Zee.Tamil.HD.APAC.in",
"ZEE.TAMIL.HD.in",
"ZEE.TAMIL.in",
"ZEE.TELUGU.HD.in",
"ZEE.TELUGU.in",
"ZEE.TELUGU.NEWS.in",
"Zee.Thirai.in",
"Zee.TV.APAC.in",
"Zee.TV.HD.Canada.in",
"ZEE.TV.HD.in",
"Zee.TV.HD.UK.in",
"Zee.TV.HD.USA.in",
"ZEE.TV.in",
"Zee.TV.ME.in",
"Zee.TV.USA.in",
"ZEE.UTTAR.PRADESH.UTTARAKHAND.in",
"ZEE.YUVA.in",
"ZEE.ZEST.in",
"ZINDAGIÂ ACTIVE.in",
"ZING.HOME.D2H..in",
"ZING.in",
"Zing.USA.in",
"ZOOM.in",
"SkySp.Cricket.uk",
"Astro.Cricket.hk",
"FoxCricket.alt.au"
}


def main():
    print("Loading source:", SOURCE_GZ)

    with gzip.open(SOURCE_GZ, "rb") as f:
        tree = ET.parse(f)

    root = tree.getroot()

    # XMLTV format uses root <tv> with <channel> and <programme>
    channels = root.findall("channel")
    programmes = root.findall("programme")

    # Keep only requested channels
    kept_channels = []
    kept_ids = set()

    for ch in channels:
        ch_id = ch.attrib.get("id", "")
        if ch_id in CHANNELS:
            kept_channels.append(ch)
            kept_ids.add(ch_id)

    kept_programmes = []
    for p in programmes:
        cid = p.attrib.get("channel", "")
        if cid in kept_ids:
            kept_programmes.append(p)

    # Create new XML
    new_root = ET.Element("tv")
    new_root.set("generator-info-name", "filtered_epg_generator")
    new_root.set("date", datetime.utcnow().strftime("%Y%m%d%H%M%S +0000"))

    for ch in kept_channels:
        new_root.append(ch)

    for p in kept_programmes:
        new_root.append(p)

    new_tree = ET.ElementTree(new_root)

    # Save xml
    new_tree.write(OUTPUT_XML, encoding="utf-8", xml_declaration=True)
    print("Saved:", OUTPUT_XML)

    # Save gz
    with open(OUTPUT_XML, "rb") as f_in, gzip.open(OUTPUT_GZ, "wb") as f_out:
        f_out.writelines(f_in)

    print("Saved:", OUTPUT_GZ)
    print("Channels kept:", len(kept_channels))
    print("Programmes kept:", len(kept_programmes))


if __name__ == "__main__":
    main()
